Repository rusefi/rusefi, pull requests merged in 2021-11, with the labels that each got.

#3504 Make getTimeNowNt even faster
  firmware/controllers/engine_controller_misc.cpp
  firmware/util/efitime.h
  unit_tests/tests/test_util.cpp
Labels: Performance

#3506 Save ~2800 bytes of RAM by not caching angle->trigger mapping
  firmware/controllers/engine_cycle/rpm_calculator.cpp
  firmware/controllers/trigger/decoders/trigger_structure.cpp
  firmware/controllers/trigger/decoders/trigger_structure.h
  firmware/controllers/trigger/trigger_decoder.cpp
  firmware/controllers/trigger/trigger_decoder.h
  unit_tests/tests/trigger/test_trigger_decoder.cpp
  unit_tests/triggers.txt
Labels: ram_shortage

#3533 delimeter is not comma
  firmware/console/status_loop.cpp
  firmware/controllers/algo/engine2.cpp
  firmware/development/engine_sniffer.cpp
  firmware/development/logic_analyzer.cpp
  firmware/development/sensor_chart.cpp
  firmware/integration/rusefi_config.txt
  firmware/util/efilib.cpp
  firmware/util/loggingcentral.cpp
  firmware/util/loggingcentral.h
  java_console/models/src/main/java/com/rusefi/config/generated/Fields.java
  java_console/models/src/main/java/com/rusefi/core/EngineState.java
Labels: after-release

#3630 Remove the EFI_NO_CONFIG_WORKING_COPY option
  firmware/config/boards/hellen/cypress/efifeatures.h
  firmware/config/boards/kinetis/efifeatures.h
  firmware/console/binary/tunerstudio.cpp
  firmware/console/binary/tunerstudio.h
  firmware/controllers/algo/engine_configuration.cpp
  firmware/controllers/core/error_handling.cpp
  firmware/controllers/engine_controller.cpp
  firmware/controllers/flash_main.cpp
  unit_tests/tests/test_tunerstudio.cpp
Labels: ram_shortage
